POST http://localhost:3002/game
Content-Type: application/json

{
  "player": ["fafa","Choreo","C","DE"]
}

###

POST http://localhost:3002/game/update
Content-Type: application/json Cookie: key=first-value

{"value" : [50110,6,7,8],
"game": "60d367e636e0bc04ee114651",
"cards": [[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16],[17,18,19,20,21,23,24],[25,26,27,28,29,30,31,32]]
}

###

GET http://localhost:3002/user/total/fafa
Accept: application/json

###


